### ISSUE TITLE
[BUG] help me 

### ISSUE THREAD

**Issue by ayeshakhan2118** [DeBos99/ytviewer#15] opened 2019-05-22 22:29 UTC
python2 main.py -u https://www.youtube.com/watch?v=5D9Ri_9EoSE -d 10 -dr firefox 
100 proxies successfully loaded!
46.0.126.134:3128
Traceback (most recent call last):
  File "main.py", line 58, in bot
    options.headless=args.headless
AttributeError: can't set attribute

**Comment by DeBos99** [comment] 2019-05-23 06:17
Duplicate of #14.

**Closed by DeBos99** 2019-05-23 06:17 UTC
Labels: bug
